import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../app/component/Header";
// import { Amplify } from "aws-amplify";
// import config from "@/amplifyconfiguration.json";

// Amplify.configure(config, {
//   ssr: true,
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Citizen Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
